// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPI.Context;

#nullable disable

namespace MyWebAPI.Migrations
{
    [DbContext(typeof(DrugDbContext))]
    partial class DrugDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyWebAPI.Models.Drug", b =>
                {
                    b.Property<int>("DrugID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DrugID"));

                    b.Property<decimal>("AWP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AcquisitionCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Dispensed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DrugClass")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPCClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Form")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NDC")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("PreviousUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RxCUI")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DrugID");

                    b.ToTable("Drugs");
                });

            modelBuilder.Entity("MyWebAPI.Models.Prescription", b =>
                {
                    b.Property<int>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScriptId"));

                    b.Property<double>("ACQ")
                        .HasColumnType("float");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ins")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("InsPay")
                        .HasColumnType("float");

                    b.Property<long>("NDC")
                        .HasColumnType("bigint");

                    b.Property<double>("Net")
                        .HasColumnType("float");

                    b.Property<string>("PF")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("PatPay")
                        .HasColumnType("float");

                    b.Property<string>("Prescriber")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("Qty")
                        .HasColumnType("float");

                    b.Property<int>("RA")
                        .HasColumnType("int");

                    b.Property<int>("RNumber")
                        .HasColumnType("int")
                        .HasColumnName("RNumber");

                    b.Property<double>("RxCui")
                        .HasColumnType("float");

                    b.Property<int>("Script")
                        .HasColumnType("int");

                    b.HasKey("ScriptId");

                    b.ToTable("Prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
